# CREATED BY https://github.com/mishmanners

# This is a basic workflow to help you get started with Actions

name: Snake Commit

# Controls when the action will run. This action runs every 6 hours.

on:
  # Controls when the action will run. Every 6 hours.
  schedule:
    # every 6 hours
    - cron: "0 */1 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

      # Run snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: skema1114
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
