name: Snake Update

on:
  workflow_dispatch:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    name: Snake Update
    runs-on: ubuntu-latest
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: skema1114
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
