name: snake commit

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
    
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@v0.0.18
        id: snake-gif
        with:
          github_user_name: skema1114
          svg_out_path: dist/github-contribution-grid-snake.svg
