name: Snake Update

on:
  workflow_dispatch:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"
 
jobs:
  build:
    name: Snake Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: skema1114
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          
      - run: git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHUB_API_TOKEN }}
          branch: master
          force: true
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_API_TOKEN }}
