name: Atualizar Todoist

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"
      
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: skema1114/todoist@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
