name: Todoist Update

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"
      
jobs:
  update-readme:
    name: Todoist Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: skema1114/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
